<?php
class VendorExport extends VendorExportBase
{
    /** @var string FieldName = VendorAds                           */
    public function __get($name)
    {
        global $SITE_URL;
        if($name == "Link")
            return $SITE_URL . "?vexport=".DgrCode::Encode($this->Id);
        if($name == "VendorAds")
        {
            if(! $this->VendorIds)
                return $this->VendorAds = "";
            $ids = implode(",",$this->VendorIds);
            $list = DB::FetchList("SELECT name_ FROM vendors WHERE id IN($ids)");
            return $this->VendorAds = implode(",",$list);
        }
        return parent::__get($name); // TODO: Change the autogenerated stub
    }
}

class VendorExportDb extends VendorExportDbBase
{
}
