<?php
class AdminOzetPage extends AppPageController
{
    public function Index()
    {
        $kisi = Kisi();
        $this->FirmaSayisi = CompanyDb::Get()->GetCount();
        $this->KullaniciSayisi = UserDb::Get()->GetCount();
        $this->VendorCount = VendorDb::Get()->GetCount();

        $this->ToplamGoruntulenme = 4;
        $this->ToplamKaydedilme = 5;


        // Son 5 aktivite
        $this->SonAktiviteler = array();

        $this->EnCokGoruntulenenKullanicilar = array();


    }
    public function SetDefaultResources()
    {
        parent::SetDefaultResources(); // TODO: Change the autogenerated stub

        $this->AddResource("dodatak/metronic/global/plugins/counterup/jquery.waypoints.min.js");
        $this->AddResource("dodatak/metronic/global/plugins/counterup/jquery.counterup.min.js");
        $this->AddResource("dodatak/metronic/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js");

    }
}
